#!/usr/bin/env python3
"""Gate: attribution ban + optional PR-template fingerprint.

Usage:
  python3 check_pr_text.py --title '...' --body-file path.md
  python3 check_pr_text.py --title '...' --body '...' --template-file tmpl.md
  cat body.md | python3 check_pr_text.py --title '...' --body-file -

Exit 0 = clean. Exit 1 = forbidden phrase and/or template mismatch.
"""

from __future__ import annotations

import argparse
import re
import sys
from typing import Iterable, Optional


# --------------------------------------------------------------------------------------
# Forbidden Patterns (Made With Cursor Gate + Close Cousins)
# --------------------------------------------------------------------------------------
FORBIDDEN: list[tuple[str, re.Pattern[str]]] = [
    (
        "made with cursor",
        re.compile(r"\bmade\s+with\s+cursor\b", re.I),
    ),
    (
        "generated by cursor",
        re.compile(r"\bgenerated\s+by\s+cursor\b", re.I),
    ),
    (
        "assisted by cursor",
        re.compile(r"\bassisted\s+by\s+cursor\b", re.I),
    ),
    (
        "cursor attribution footer",
        re.compile(r"https?://cursor\.com/\S*made", re.I),
    ),
    # Suite / process meta — must not appear in upstream PR text
    (
        "live codex run",
        re.compile(r"\blive\s+codex\s+run\b", re.I),
    ),
    (
        "codex run",
        re.compile(r"\bcodex\s+run\b", re.I),
    ),
    (
        "unit coverage only",
        re.compile(r"\bunit\s+coverage\s+only\b", re.I),
    ),
    (
        "this path does not require",
        re.compile(r"\bthis\s+path\s+does\s+not\s+require\b", re.I),
    ),
    (
        "does not require an api key",
        re.compile(r"\bdoes\s+not\s+require\s+an?\s+api\s+key\b", re.I),
    ),
    (
        "wrk-e2e meta",
        re.compile(r"\bwrk-e2e\b", re.I),
    ),
    (
        "wrk-begin meta",
        re.compile(r"\bwrk-begin\b", re.I),
    ),
    (
        "legacy skill meta",
        re.compile(r"\boss-(e2e|begin|bug|feat|rev|pr|push|ci|comp)\b", re.I),
    ),
    (
        "legacy host meta",
        re.compile(r"\bcloud\s+agent\b", re.I),
    ),
    (
        "na pipeline excuse",
        re.compile(
            r"\bn/?a\s*[—\-–]\s*.{0,80}(codex|unit\s+coverage|api\s+key|this\s+path)\b",
            re.I,
        ),
    ),
]

_HEADING_RE = re.compile(r"^(#{1,3})\s+(.+?)\s*$", re.M)
_CHECKBOX_RE = re.compile(r"^[\t ]*[-*]\s*\[[ xX]\]\s*(.+?)\s*$", re.M)
_HTML_COMMENT_RE = re.compile(r"<!--.*?-->", re.S)
_OPTIONAL_SECTION_HINT = re.compile(
    r"delete this section|only fill this out if|only fill this if",
    re.I,
)


def find_hits(text: str) -> list[tuple[str, str]]:
    hits: list[tuple[str, str]] = []
    for label, pat in FORBIDDEN:
        for m in pat.finditer(text or ""):
            snippet = m.group(0)
            hits.append((label, snippet))
    return hits


def check(title: str, body: str) -> list[str]:
    messages: list[str] = []
    for where, blob in (("title", title), ("body", body)):
        for label, snippet in find_hits(blob):
            messages.append(f"{where}: forbidden ({label}): {snippet!r}")
    return messages


def _norm_ws(s: str) -> str:
    return re.sub(r"\s+", " ", (s or "").strip())


def _strip_comments(text: str) -> str:
    return _HTML_COMMENT_RE.sub("", text or "")


def _sections(template: str) -> list[tuple[str, str, str]]:
    """
    Split template into (heading_line_without_hashes, full_heading_match, body).
    heading text keeps emojis / punctuation.
    """
    text = template.replace("\r\n", "\n")
    matches = list(_HEADING_RE.finditer(text))
    out: list[tuple[str, str, str]] = []
    for i, m in enumerate(matches):
        start = m.end()
        end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        heading = m.group(2).strip()
        out.append((heading, m.group(0).rstrip(), text[start:end]))
    return out


def _section_optional(section_body: str) -> bool:
    # Only the leading HTML comment(s) before real content
    head = section_body.lstrip()[:800]
    comments = _HTML_COMMENT_RE.findall(head)
    if not comments:
        return False
    blob = "\n".join(comments)
    return bool(_OPTIONAL_SECTION_HINT.search(blob))


def template_fingerprint_errors(body: str, template: str) -> list[str]:
    """
    When a checkout PR template exists, the draft must keep its skeleton:
    required headings + checkbox labels (including emoji prefixes).
    Optional sections (template comment says delete / only fill if …) may be omitted.
    """
    if not (template or "").strip():
        return ["template: empty template file"]

    body_n = body.replace("\r\n", "\n")
    body_plain = _strip_comments(body_n)
    errors: list[str] = []

    for heading, _full, section_body in _sections(template):
        if _section_optional(section_body):
            continue
        # Heading must appear as a markdown heading with the same visible text
        if not re.search(
            rf"^#{{1,3}}\s+{re.escape(heading)}\s*$",
            body_plain,
            re.M,
        ):
            errors.append(f"template: missing heading {heading!r}")

    # Checkbox labels from non-optional sections only
    for heading, _full, section_body in _sections(template):
        if _section_optional(section_body):
            continue
        for label in _CHECKBOX_RE.findall(section_body):
            # Comments in template labels (e.g. platform hint) are not required in body
            label_n = _norm_ws(_strip_comments(label)).rstrip(":").strip()
            if not label_n:
                continue
            # Label must appear after a checkbox marker in the body.
            # Allow trailing platform notes after the label (e.g. ": Ubuntu").
            if not re.search(
                rf"^[\t ]*[-*]\s*\[[ xX]\]\s*{re.escape(label_n)}(?:\s|$|:)",
                body_plain,
                re.M,
            ):
                errors.append(f"template: missing checkbox label {label_n!r}")

    return errors


def check_all(
    title: str,
    body: str,
    template: Optional[str] = None,
) -> list[str]:
    msgs = check(title, body)
    if template is not None:
        msgs.extend(template_fingerprint_errors(body, template))
    return msgs


def _read_text(path: str) -> str:
    if path == "-":
        return sys.stdin.read()
    with open(path, encoding="utf-8") as f:
        return f.read()


def _read_body(args: argparse.Namespace) -> str:
    if args.body is not None:
        return args.body
    return _read_text(args.body_file)


def main(argv: Iterable[str] | None = None) -> int:
    p = argparse.ArgumentParser(
        description="wrk-pr attribution + template fingerprint gate"
    )
    p.add_argument("--title", required=True)
    g = p.add_mutually_exclusive_group(required=True)
    g.add_argument("--body")
    g.add_argument("--body-file", help="Path to body markdown, or - for stdin")
    p.add_argument(
        "--template-file",
        help="Checkout PR template path. When set, draft must keep its skeleton.",
    )
    args = p.parse_args(list(argv) if argv is not None else None)

    body = _read_body(args)
    template = None
    if args.template_file:
        template = _read_text(args.template_file)

    msgs = check_all(args.title, body, template=template)
    if msgs:
        print("wrk-pr check FAILED — fix before delivery:", file=sys.stderr)
        for m in msgs:
            print(f"  - {m}", file=sys.stderr)
        return 1
    if template is not None:
        print("wrk-pr check OK — attribution clean; template fingerprint matched")
    else:
        print("wrk-pr check OK — no Made with Cursor / Cursor attribution found")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
